name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create .env file from secret
      run: echo "FOOTBALL_API_KEY=${{ secrets.API_KEY }}" > .env

    - name: Set Docker tag
      id: vars
      run: |
        TAG=$(echo "${GITHUB_REF##*/}")
        echo "tag=${TAG}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          yuvalost/football-fixtures-app:latest
          yuvalost/football-fixtures-app:${{ steps.vars.outputs.tag }}
