name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create .env file from secret
      run: echo "${{ secrets.API_KEY }}" > .env

    - name: Build and push Docker image
      run: |
        docker build -t yuvalost/football-fixtures-app:latest .
        docker push yuvalost/football-fixtures-app:latest
